# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
